server.port = 8761
eureka.instance.hostname=localhost
eureka.instance.instance-id=service-register:8761
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://127.0.0.1:8762/eureka/