services:
  kafka-1:
    image: apache/kafka:latest
    container_name: waybill-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "4L622nShTUiBenVKWIRCkg"
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    restart: always

  kafka-2:
    image: apache/kafka:latest
    container_name: waybill-kafka-2
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "4L622nShTUiBenVKWIRCkg"
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    restart: always

  kafka-3:
    image: apache/kafka:latest
    container_name: waybill-kafka-3
    ports:
      - "9096:9096"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "4L622nShTUiBenVKWIRCkg"
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: waybill-kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: waybill-ha-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092,kafka-2:29092,kafka-3:29092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  frontend-1:
    image: khanhnv26/frontend:1.0
    container_name: waybill-frontend-1
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: ["node", "server.js", "3000"]
    restart: always

  frontend-2:
    image: khanhnv26/frontend:1.0
    container_name: waybill-frontend-2
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    command: ["node", "server.js", "3001"]
    restart: always

  nginx-gateway-lb:
    image: nginx:alpine
    container_name: waybill-nginx-gateway-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - frontend-1
      - frontend-2
    restart: always

  redis:
      image: redis:alpine
      container_name: redis
      ports:
        - "6379:6379"
      restart: always

  sqlserver-replica:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: waybill-sqlserver-replica
    ports:
      - "2433:1433"
    environment:
      SA_PASSWORD: "Replica@123456"
      ACCEPT_EULA: "Y"
    restart: always

  eureka-peer1:
    image: khanhnv26/service-registry:1.0
    container_name: waybill-eureka-peer1
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_INSTANCE_HOSTNAME=eureka-peer1
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer2:8762/eureka/
    restart: always

  eureka-peer2:
    image: khanhnv26/service-registry:1.0
    container_name: waybill-eureka-peer2
    ports:
      - "8762:8762"
    environment:
      - SERVER_PORT=8762
      - EUREKA_INSTANCE_HOSTNAME=eureka-peer2
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/
    restart: always

  api-gateway-1:
    image: khanhnv26/api-gateway:1.0
    container_name: waybill-api-gateway-1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - eureka-peer1
      - eureka-peer2
      - redis
    restart: always

  api-gateway-2:
    image: khanhnv26/api-gateway:1.0
    container_name: waybill-api-gateway-2
    ports:
      - "8088:8088"
    environment:
      - SERVER_PORT=8088
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - eureka-peer1
      - eureka-peer2
      - redis
    restart: always

  auth-service:
    image: khanhnv26/auth-service:1.0
    container_name: waybill-auth-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=auth_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - eureka-peer1
      - eureka-peer2
      - redis
      - sqlserver-replica
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  customer-service:
    image: khanhnv26/customer-service:1.0
    container_name: waybill-customer-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=customer_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
    restart: always

  shipment-service:
    image: khanhnv26/shipment-service:1.0
    container_name: waybill-shipment-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=shipment_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  routing-service:
    image: khanhnv26/routing-service:1.0
    container_name: waybill-routing-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=routing_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
      - redis
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  tracking-service:
    image: khanhnv26/tracking-service:1.0
    container_name: waybill-tracking-service-1
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=tracking_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_PRIMARY_USERNAME=sa
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=Replica@123456

      - SPRING_DATASOURCE_REPLICA_JDBC_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=tracking_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_REPLICA_USERNAME=sa
      - SPRING_DATASOURCE_REPLICA_PASSWORD=Replica@123456

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - sqlserver-replica
      - redis
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  tracking-service-2:
    image: khanhnv26/tracking-service:1.0
    container_name: waybill-tracking-service-2
    ports:
      - "8094:8094"
    environment:
      - SERVER_PORT=8094
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=tracking_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_PRIMARY_USERNAME=sa
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=Replica@123456

      - SPRING_DATASOURCE_REPLICA_JDBC_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=tracking_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_REPLICA_USERNAME=sa
      - SPRING_DATASOURCE_REPLICA_PASSWORD=Replica@123456

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - sqlserver-replica
      - redis
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  notification-service:
    image: khanhnv26/notification-service:1.0
    container_name: waybill-notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=notification_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - redis
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  audit-service:
    image: khanhnv26/audit-service:1.0
    container_name: waybill-audit-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=audit_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always

  shipper-service:
    image: khanhnv26/shipper-service:1.0
    container_name: waybill-shipper-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=shipper_db;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
    restart: always

  report-service:
    image: khanhnv26/report-service:1.0
    container_name: waybill-report-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-replica:1433;databaseName=report_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Replica@123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    depends_on:
      - sqlserver-replica
      - eureka-peer1
      - eureka-peer2
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always















