apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sqlserver-network-policy
  namespace: waybill
spec:
  podSelector:
    matchLabels:
      app: sqlserver-replica
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - auth-service
                  - customer-service
                  - shipment-service
                  - routing-service
                  - tracking-service
                  - notification-service
                  - audit-service
                  - shipper-service
                  - report-service
                  - payment-service
                  - rating-service
                  - support-service
                  - sqlserver-init-db
      ports:
        - protocol: TCP
          port: 1433
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  namespace: waybill
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - api-gateway
                  - shipment-service
                  - tracking-service
                  - customer-service
                  - notification-service
                  - auth-service
                  - payment-service
                  - routing-service
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: waybill
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
