spring.application.name=payment-service
server.port=8095

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=payment_db;encrypt=true;trustServerCertificate=true;}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sa}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/,http://localhost:8762/eureka/}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.baseline-description=Initial Database

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=payment-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=org.app.shipmentservice.dto.event.ShipmentStatusUpdatedEvent:org.app.paymentservice.dto.event.ShipmentStatusUpdatedEvent,org.app.routingservice.dto.event.ShipmentStatusUpdatedEvent:org.app.paymentservice.dto.event.ShipmentStatusUpdatedEvent,org.app.trackingservice.dto.event.ShipmentStatusUpdatedEvent:org.app.paymentservice.dto.event.ShipmentStatusUpdatedEvent

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

vietqr.bank-code=${VIETQR_BANK_CODE:MB}
vietqr.account-no=${VIETQR_ACCOUNT_NO:0987654321}
vietqr.account-name=${VIETQR_ACCOUNT_NAME:VNPT POST LOGISTICS}
vietqr.template=${VIETQR_TEMPLATE:compact2}
vietqr.webhook-secret=${VIETQR_WEBHOOK_SECRET:vnpt_waybill_secret_2026}
