events {
 worker_connections 1024;
}
http {

    upstream frontend_cluster {
        server host.docker.internal:3000 max_fails=3 fail_timeout=5s;
        server host.docker.internal:3001 max_fails=3 fail_timeout=5s;
    }




    upstream gateway_cluster {
        server host.docker.internal:8080 max_fails=3 fail_timeout=5s;
        server host.docker.internal:8088 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 80;
        server_name localhost;


        error_page 403 /error.html?code=403;
        error_page 404 /error.html?code=404;
        error_page 500 /error.html?code=500;
        error_page 502 /error.html?code=502;
        error_page 503 /error.html?code=503;


        location = /error.html {
            root /usr/share/nginx/html;
        }

        location /api/ {
            proxy_pass http://gateway_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_502 http_503;
        }

        location / {
            proxy_pass http://frontend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_502;
            proxy_intercept_errors on;
        }
    }
}
