apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: waybill
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: khanhnv26/notification-service:9aa561bd217ece600edfa523355a5d917a4d0ccf
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://sqlserver-replica:1433;databaseName=notification_db;encrypt=true;trustServerCertificate=true;"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: waybill-runtime
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-peer1:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "${HOSTNAME}:${server.port}"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: waybill-runtime
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: waybill-runtime
                  key: mail-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: waybill
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 8085
      targetPort: 8085
