apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: waybill
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: khanhnv26/payment-service:0d91eb22e9c84afe69a00eb4c4de37fa7d00855c
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://sqlserver-replica:1433;databaseName=payment_db;encrypt=true;trustServerCertificate=true;"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: waybill-runtime
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-peer1:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "${HOSTNAME}:${server.port}"
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: waybill
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8095
      targetPort: 8095
