apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
  namespace: waybill
  labels:
    app: shipment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      labels:
        app: shipment-service
    spec:
      containers:
        - name: shipment-service
          image: khanhnv26/shipment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlserver://sqlserver-replica:1433;databaseName=shipment_db;encrypt=true;trustServerCertificate=true;"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Replica@123456"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-peer1:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
  namespace: waybill
spec:
  type: ClusterIP
  selector:
    app: shipment-service
  ports:
    - port: 8082
      targetPort: 8082
