apiVersion: v1
kind: ConfigMap
metadata:
  name: waybill-config
  namespace: waybill
data:
  AI_BASE_URL: "http://host.docker.internal:11434/v1"
  AI_MODEL: "qwen2.5:3b"
  MINIO_PUBLIC_URL: "https://storage.waybill.vn"
